name: postprocessing
# Environment file for summarize_results.py script. Called by the main workflow.

channels:
  - conda-forge
  - defaults

channel_priority: strict

dependencies:
  - python=3.12
  - pint
  - pyvista
  - rdflib
  - matplotlib
  - pandas
  - numpy
  - pip
  - pip:
      - roc-validator
      - rohub 