name: mesh-generation
# Environment file for create_mesh.py script. Called by the main workflow.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.12
  - pint
  - python-gmsh