name: fenics_simulation
# Environment file for fenics simulation scripts. Called by fenics tool workflow.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.12
  - fenics-dolfinx=0.9.*
  - mpich
  - petsc4py
  - pint
  - python-gmsh
  - sympy
